project_id = "azqopaixiweqtenuanas"

[functions.google-auth-start]
verify_jwt = false

[functions.google-auth-callback]

[functions.google-create-event]

[functions.google-revoke]

[functions.send-email]
verify_jwt = true

[functions.send-meeting-invitation]
verify_jwt = true

[functions.create-notification]
verify_jwt = false

[functions.track-profile-view]
verify_jwt = false
